spring:
  application:
    name: zoi-drive
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/drive
    username: postgres
    password: 123456
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  mail:
    host: localhost
    port: 1025
    username: test
    password: test
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
server:
  port: 9088
  system:
    endpoint: http://localhost:9088
    default-storage: 1000.00

sa-token:
  token-name: Token
  # Token有效期：30天
  timeout: 2592000
  # 最低活动频率
  active-timeout: -1
  is-concurrent: false
  is-share: true
  token-style: uuid
  is-log: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-handlers-package: com.zoi.drive.handler.type
  global-config:
    db-config:
      # 逻辑删除相关配置
      logic-delete-value: true
      logic-not-delete-value: false
      logic-delete-field: isDeleted

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: zoi-drive-system

aria:
  url: http://localhost:16800/jsonrpc
  secret: zoidrive
