spring:
  application:
    name: Drive
  datasource:
    url: jdbc:postgresql://localhost:5432/drive
    username: postgres
    password: 123456

server:
  port: 9088

sa-token:
  token-name: Token
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true
